import { verifyAccessJwt, json, now, uuid } from './lib.mjs';
const BASE='https://api.firecrawl.dev/v2'; const MAX_QUERY=500, MAX_URL=2048;
function cors(request,env){const origin=request.headers.get('origin')||'';const allowed=String(env.ALLOWED_ORIGINS||'').split(',').map(s=>s.trim()).filter(Boolean);const h={'Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'content-type, cf-access-jwt-assertion, x-arc-case-id','Vary':'Origin'};if(origin&&allowed.includes(origin))h['Access-Control-Allow-Origin']=origin;return h}
async function user(request,env){const id=await verifyAccessJwt(request.headers.get('Cf-Access-Jwt-Assertion')||'',env);const u=await env.DB.prepare('SELECT * FROM legal_users WHERE email=?').bind(id.email).first();if(!u||u.status!=='active'||u.role==='pending')throw Object.assign(new Error('Account pending or disabled.'),{status:403});return u}
async function access(env,u,caseId){if(!caseId)throw Object.assign(new Error('Active ARC case required.'),{status:400});if(['administrator','supervisor'].includes(u.role))return;const a=await env.DB.prepare('SELECT 1 x FROM case_assignments WHERE case_id=? AND email=?').bind(caseId,u.email).first();if(!a)throw Object.assign(new Error('You are not assigned to this ARC case.'),{status:403})}
function publicUrl(v){let u;try{u=new URL(v)}catch{throw Object.assign(new Error('Invalid URL.'),{status:400})}if(!['http:','https:'].includes(u.protocol))throw Object.assign(new Error('Only HTTP(S) URLs are allowed.'),{status:400});const h=u.hostname.toLowerCase();if(h==='localhost'||h==='::1'||/^127\./.test(h)||/^10\./.test(h)||/^192\.168\./.test(h)||/^169\.254\./.test(h)||/^172\.(1[6-9]|2\d|3[01])\./.test(h)||h.endsWith('.local')||h==='metadata.google.internal')throw Object.assign(new Error('Private or local URLs are not allowed.'),{status:400});return u.toString()}
async function call(env,path,body){if(!env.FIRECRAWL_API_KEY)throw Object.assign(new Error('Firecrawl is not configured.'),{status:503});const r=await fetch(BASE+path,{method:'POST',headers:{authorization:'Bearer '+env.FIRECRAWL_API_KEY,'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json().catch(()=>({error:'Invalid provider response'}));if(!r.ok)throw Object.assign(new Error(j.error||j.message||('Firecrawl HTTP '+r.status)),{status:r.status===429?429:502});return j}
async function hash(s){const b=new TextEncoder().encode(String(s||''));const d=await crypto.subtle.digest('SHA-256',b);return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function log(env,u,route,caseId,ok,n=0){try{await env.DB.prepare('INSERT INTO provider_log (id,at,actor,provider,route,case_id,request_chars,response_chars,ok) VALUES (?,?,?,?,?,?,?,?,?)').bind(uuid(),now(),u.email,'firecrawl',route,caseId||'',n,0,ok?1:0).run()}catch{}}
export async function handle(request,env){const h=cors(request,env);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:h});try{const u=await user(request,env),url=new URL(request.url),path=url.pathname.replace(/^\/research-api\/?/,'').replace(/\/+$/,'');if(path==='status'&&request.method==='GET')return json({ok:true,configured:!!env.FIRECRAWL_API_KEY,provider:'firecrawl',role:u.role},200,h);const caseId=(request.headers.get('X-ARC-Case-ID')||'').trim();await access(env,u,caseId);if(path==='search'&&request.method==='POST'){const b=await request.json(),q=String(b.query||'').trim();if(!q||q.length>MAX_QUERY)throw Object.assign(new Error('Search query must be 1-'+MAX_QUERY+' characters.'),{status:400});const out=await call(env,'/search',{query:q,limit:Math.min(Math.max(Number(b.limit)||5,1),10),scrapeOptions:{formats:['markdown']}});await log(env,u,'search',caseId,true,q.length);return json({success:true,caseId,provider:'firecrawl',retrievedAt:now(),result:out},200,h)}if(path==='scrape'&&request.method==='POST'){const b=await request.json(),target=publicUrl(String(b.url||'').slice(0,MAX_URL));const out=await call(env,'/scrape',{url:target,formats:['markdown'],onlyMainContent:b.onlyMainContent!==false});await log(env,u,'scrape',caseId,true,target.length);return json({success:true,caseId,provider:'firecrawl',retrievedAt:now(),sourceUrl:target,result:out},200,h)}if(path==='save'&&request.method==='POST'){const b=await request.json(),source=publicUrl(String(b.sourceUrl||'').slice(0,MAX_URL)),content=String(b.contentMarkdown||'').slice(0,2_000_000);if(!content)throw Object.assign(new Error('No research content supplied.'),{status:400});const rid=uuid(),sha=await hash(content);await env.DB.prepare(`INSERT INTO web_research_records (research_id,case_id,source_url,title,provider,retrieved_at,retrieved_by,content_markdown,content_hash,related_issue_id,verification_status,notes,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(rid,caseId,source,String(b.title||'').slice(0,500),'firecrawl',b.retrievedAt||now(),u.email,content,sha,String(b.relatedIssueId||''),'Unverified',String(b.notes||'').slice(0,4000),now()).run();return json({success:true,researchId:rid,sha256:sha,status:'Unverified'},201,h)}if(path==='list'&&request.method==='GET'){const q=await env.DB.prepare('SELECT research_id,source_url,title,provider,retrieved_at,retrieved_by,content_hash,related_issue_id,verification_status,notes FROM web_research_records WHERE case_id=? ORDER BY retrieved_at DESC').bind(caseId).all();return json({results:q.results||[]},200,h)}throw Object.assign(new Error('Research endpoint not found.'),{status:404})}catch(e){return json({error:e.message||'Research request failed.'},e.status||500,h)}}
export default{fetch:handle};
