(function(){
"use strict";
const STORAGE="arc_report_package_builder_v1";
const SECTION_DEFS=[
["background","Case Background"],["scope","Assignment and Scope"],["facts","Statement of Facts"],["police","Police Report Summary"],["conducted","Investigation Conducted"],["parties","Parties and Witnesses"],["evidence","Evidence Reviewed"],["timeline","Master Timeline"],["interviews","Interviews and Contact Attempts"],["discovery","Discovery Issues"],["contradictions","Contradictions"],["missing","Missing Evidence"],["custody","Chain-of-Custody Issues"],["forensic","Forensic Findings"],["legal","Legal Questions"],["strategy","Investigation Strategy"],["findings","Approved Findings"],["recommendations","Recommendations"],["exhibits","Exhibit Index"]
];
const state={caseContext:{},sources:[],draft:null};
const $=id=>document.getElementById(id);
function clean(v,m){const s=String(v==null?"":v).trim();return m?s.slice(0,m):s}
function esc(v){return clean(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function uid(){return crypto&&crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function caseId(){const c=state.caseContext||{};return clean(c.caseId||c.id||c.docket||c.matter||"unassigned",180)}
function blankDraft(){const sections={};SECTION_DEFS.forEach(x=>sections[x[0]]="");return{schema:"arc-report-package",schemaVersion:1,id:uid(),caseId:caseId(),title:"Final Investigation Report",type:"Final Investigation Report",preparedFor:"",confidentiality:"Attorney Work Product - Confidential",summary:"",selectedSourceIds:[],sections,locked:false,updatedAt:null}}
function getCase(){return window.ARCUnified&&typeof window.ARCUnified.getCase==="function"?(window.ARCUnified.getCase()||{}):(window.ARC_CASE_CONTEXT||{})}
function setStatus(msg,tone){$("rpStatus").className="rp-status"+(tone?" "+tone:"");$("rpStatus").textContent=msg}
function addSource(map,s){const title=clean(s.title||s.name,300),text=clean(s.text||s.preview||s.description||"",50000);if(!title&&!text)return;const row={id:clean(s.id,180)||uid(),kind:clean(s.kind||s.type||"record",80),title:title||"Untitled source",citation:clean(s.citation||s.source||"Not Listed",600)||"Not Listed",status:clean(s.status||"available",80),text,approved:Boolean(s.approved||/approved|final|verified/i.test(s.status||s.reviewStatus||"")),meta:s.meta||s.originalMetadata||{}};map.set([row.kind,row.id,row.title].join("::").toLowerCase(),row)}
async function collectSources(){const map=new Map(),c=state.caseContext||{};(c.uploadedFiles||[]).forEach(f=>addSource(map,{id:f.id,kind:"evidence",title:f.name,type:f.type,citation:f.category||"Uploaded evidence",status:(f.extraction&&f.extraction.status)||"available",text:(f.extraction&&(f.extraction.preview||(f.extraction.facts||[]).map(x=>x.text).join("\n")))||"",meta:f}));((c.intake&&c.intake.extractions)||[]).forEach(r=>addSource(map,{id:r.id,kind:"initial-discovery",title:r.name,type:r.category,citation:r.category||"Intake extraction",status:r.status,text:r.preview||(r.facts||[]).map(x=>x.text).join("\n"),meta:r}));if(window.ARCUnified&&typeof window.ARCUnified.getCaseReports==="function"){(window.ARCUnified.getCaseReports(c)||[]).forEach(r=>addSource(map,{id:r.id,kind:"investigator-report",title:r.title,type:r.reportType,citation:r.source||"ARC report",status:r.reviewStatus||"draft",text:r.text||r.html||"",meta:r}))}if(window.ARCReportAssets&&typeof window.ARCReportAssets.list==="function"){try{(await window.ARCReportAssets.list()).forEach(a=>addSource(map,{id:a.id,kind:"report-asset",title:a.title,type:a.type,citation:a.citation||a.source||"Report asset",status:a.status,text:[a.description,a.source,a.citation].filter(Boolean).join("\n"),meta:a}))}catch(e){}}state.sources=Array.from(map.values());}
function loadDraft(){let d=null;try{const all=JSON.parse(localStorage.getItem(STORAGE)||"{}");d=all[caseId()]||null}catch(e){}state.draft=Object.assign(blankDraft(),d||{});state.draft.sections=Object.assign(blankDraft().sections,(d&&d.sections)||{});}
function saveDraft(){capture();state.draft.updatedAt=new Date().toISOString();let all={};try{all=JSON.parse(localStorage.getItem(STORAGE)||"{}")||{}}catch(e){}all[caseId()]=state.draft;localStorage.setItem(STORAGE,JSON.stringify(all));setStatus("Master report saved locally for this active case.");renderManifest()}
function capture(){state.draft.title=clean($("rpTitle").value,300);state.draft.type=clean($("rpType").value,120);state.draft.preparedFor=clean($("rpPreparedFor").value,300);state.draft.confidentiality=clean($("rpConfidentiality").value,180);state.draft.summary=clean($("rpSummary").value,10000);document.querySelectorAll("[data-section-key]").forEach(n=>state.draft.sections[n.dataset.sectionKey]=clean(n.value,50000));state.draft.selectedSourceIds=Array.from(document.querySelectorAll("[data-source-id]:checked")).map(n=>n.dataset.sourceId)}
function hydrate(){$("rpTitle").value=state.draft.title;$("rpType").value=state.draft.type;$("rpPreparedFor").value=state.draft.preparedFor;$("rpConfidentiality").value=state.draft.confidentiality;$("rpSummary").value=state.draft.summary}
function renderSources(){const box=$("rpSources");if(!state.sources.length){box.innerHTML='<div class="rp-empty">No case sources were found. Open a case and add discovery, evidence, or reports first.</div>';return}box.innerHTML=state.sources.map(s=>`<div class="rp-source"><label><input type="checkbox" data-source-id="${esc(s.id)}" ${state.draft.selectedSourceIds.includes(s.id)?"checked":""}><span><strong>${esc(s.title)}</strong><small>${esc(s.kind)} · ${esc(s.status)} · ${esc(s.citation)}</small></span></label></div>`).join("")}
function renderSections(){$("rpSections").innerHTML=SECTION_DEFS.map(x=>`<article class="rp-section"><div class="rp-section-head"><h3>${esc(x[1])}</h3><span class="rp-badge ${state.draft.sections[x[0]]?"ready":"draft"}">${state.draft.sections[x[0]]?"Included":"Draft"}</span></div><textarea class="rp-textarea" data-section-key="${esc(x[0])}" placeholder="Enter approved, source-supported content for ${esc(x[1])}.">${esc(state.draft.sections[x[0]]||"")}</textarea></article>`).join("")}
function selectedSources(){return state.sources.filter(s=>state.draft.selectedSourceIds.includes(s.id))}
function reportHtmlBody(interactive){capture();const c=state.caseContext||{};const sections=SECTION_DEFS.filter(x=>clean(state.draft.sections[x[0]])).map(x=>`<section id="sec-${esc(x[0])}" class="report-section"><h2>${esc(x[1])}</h2>${paragraphs(state.draft.sections[x[0]])}</section>`).join("");const sourceRows=selectedSources().map(s=>`<tr><td>${esc(s.title)}</td><td>${esc(s.kind)}</td><td>${esc(s.citation)}</td><td>${esc(s.status)}</td></tr>`).join("");return `<header class="report-cover"><div class="conf">${esc(state.draft.confidentiality)}</div><h1>${esc(state.draft.title)}</h1><p>${esc(c.matter||c.caseName||c.clientName||"Active ARC Case")}</p><p>${esc(c.docket||c.docketNumber||"")}</p><p>Prepared for: ${esc(state.draft.preparedFor||"Not Listed")}</p><p>Generated: ${esc(new Date().toLocaleString())}</p></header>${state.draft.summary?`<section id="sec-summary" class="report-section"><h2>Executive Summary</h2>${paragraphs(state.draft.summary)}</section>`:""}${sections}<section id="sec-sources" class="report-section"><h2>Selected Source Register</h2><table><thead><tr><th>Source</th><th>Type</th><th>Citation</th><th>Status</th></tr></thead><tbody>${sourceRows||'<tr><td colspan="4">No sources selected.</td></tr>'}</tbody></table></section>`}
function paragraphs(text){return clean(text).split(/\n{2,}/).map(p=>`<p>${esc(p).replace(/\n/g,"<br>")}</p>`).join("")}
function renderPreview(){capture();$("rpPreview").innerHTML=reportHtmlBody(false);renderChecks();renderManifest()}
function renderChecks(){capture();const checks=[
[Boolean(state.draft.title),"Report title is present"],[Boolean(state.draft.type),"Report type is selected"],[state.draft.selectedSourceIds.length>0,"At least one source is selected"],[Boolean(state.draft.summary),"Executive summary is completed"],[Boolean(state.draft.sections.findings),"Approved findings section is completed"],[Boolean(state.draft.sections.evidence),"Evidence reviewed section is completed"],[!Object.values(state.draft.sections).some(v=>/\[(?:insert|todo|placeholder)|\bTBD\b/i.test(v)),"No unresolved placeholders detected"]
];$("rpChecks").innerHTML=checks.map(c=>`<div class="rp-source"><strong>${c[0]?"PASS":"REVIEW"}</strong><small>${esc(c[1])}</small></div>`).join("")}
function attorneyDocument(){capture();const tabs=[...["summary","Overview"],...SECTION_DEFS.filter(x=>clean(state.draft.sections[x[0]])),["sources","Sources"]];const nav=tabs.map((x,i)=>`<button data-tab="sec-${esc(x[0])}" class="${i===0?"active":""}">${esc(x[1])}</button>`).join("");return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(state.draft.title)}</title><style>${interactiveCss()}</style></head><body><header><h1>${esc(state.draft.title)}</h1><input id="search" placeholder="Search report"><nav>${nav}</nav></header><main>${reportHtmlBody(true)}</main><script>${interactiveJs()}<\/script></body></html>`}
function interactiveCss(){return `*{box-sizing:border-box}body{margin:0;background:#f5f7fb;color:#111827;font-family:Arial,sans-serif}header{position:sticky;top:0;background:#071426;color:#fff;padding:16px;z-index:3}header h1{margin:0 0 10px;font-family:Georgia,serif}header input{width:min(480px,100%);padding:9px;border-radius:5px;border:0}nav{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}nav button{border:1px solid #52657b;background:#10253c;color:#fff;padding:7px 10px;border-radius:5px;cursor:pointer}nav button.active{background:#d49a1f;color:#111}main{max-width:1100px;margin:auto;padding:20px}.report-cover,.report-section{background:#fff;border:1px solid #d8dee8;border-radius:7px;padding:22px;margin-bottom:14px}.report-cover{text-align:center}.conf{font-weight:bold;color:#8a5900}.report-section{display:none}.report-section.active{display:block}.report-section h2{font-family:Georgia,serif}table{border-collapse:collapse;width:100%}th,td{border-bottom:1px solid #ddd;text-align:left;padding:8px}.hit{outline:3px solid #d49a1f}@media print{header{position:static;background:#fff;color:#000}header input,nav{display:none}.report-section{display:block!important;border:0;padding:0}.report-cover{border:0}}`}
function interactiveJs(){return `(function(){var buttons=[].slice.call(document.querySelectorAll('nav button'));var sections=[].slice.call(document.querySelectorAll('.report-section'));function show(id){sections.forEach(function(s){s.classList.toggle('active',s.id===id)});buttons.forEach(function(b){b.classList.toggle('active',b.dataset.tab===id)})}buttons.forEach(function(b){b.addEventListener('click',function(){show(b.dataset.tab)})});show(buttons[0]?buttons[0].dataset.tab:'sec-summary');document.getElementById('search').addEventListener('input',function(){var q=this.value.toLowerCase().trim();sections.forEach(function(s){s.classList.remove('hit')});if(!q)return;var hit=sections.find(function(s){return s.textContent.toLowerCase().indexOf(q)>=0});if(hit){show(hit.id);hit.classList.add('hit')}})})();`}
function download(name,blob){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}
function safeName(){return clean((state.caseContext.matter||state.caseContext.caseName||"ARC_Case").replace(/[^a-z0-9_-]+/gi,"_"),80)||"ARC_Case"}
function renderManifest(){capture();const files=["formal PDF generated through Print / Save PDF","interactive_attorney_report.html","index.html","report/report_data.json","report/report_print.html","README.html","integrity/manifest.json","integrity/sha256_checksums.txt"];$("rpManifest").innerHTML=`<p><strong>Master report ID:</strong> ${esc(state.draft.id)}</p><p><strong>Case:</strong> ${esc(caseId())}</p><p><strong>Selected sources:</strong> ${state.draft.selectedSourceIds.length}</p><p><strong>Included sections:</strong> ${Object.values(state.draft.sections).filter(Boolean).length}</p><ul>${files.map(f=>`<li>${esc(f)}</li>`).join("")}</ul>`}
function crcTable(){const t=[];for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;t[n]=c>>>0}return t}const CRCT=crcTable();function crc32(bytes){let c=0xffffffff;for(let i=0;i<bytes.length;i++)c=CRCT[(c^bytes[i])&255]^(c>>>8);return(c^0xffffffff)>>>0}
function u16(n){return[n&255,(n>>>8)&255]}function u32(n){return[n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255]}
function makeZip(files){const enc=new TextEncoder(),parts=[],central=[];let offset=0;Object.keys(files).forEach(name=>{const nb=enc.encode(name),data=typeof files[name]==="string"?enc.encode(files[name]):files[name],crc=crc32(data),local=new Uint8Array([...u32(0x04034b50),...u16(20),...u16(0),...u16(0),...u16(0),...u16(0),...u32(crc),...u32(data.length),...u32(data.length),...u16(nb.length),...u16(0),...nb]);parts.push(local,data);central.push(new Uint8Array([...u32(0x02014b50),...u16(20),...u16(20),...u16(0),...u16(0),...u16(0),...u16(0),...u32(crc),...u32(data.length),...u32(data.length),...u16(nb.length),...u16(0),...u16(0),...u16(0),...u16(0),...u32(0),...u32(offset),...nb]));offset+=local.length+data.length});const centralOffset=offset,centralSize=central.reduce((n,x)=>n+x.length,0);parts.push(...central,new Uint8Array([...u32(0x06054b50),...u16(0),...u16(0),...u16(central.length),...u16(central.length),...u32(centralSize),...u32(centralOffset),...u16(0)]));return new Blob(parts,{type:"application/zip"})}
async function sha256Text(text){const buf=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(text));return Array.from(new Uint8Array(buf)).map(b=>b.toString(16).padStart(2,"0")).join("")}
async function buildZip(){capture();const attorney=attorneyDocument(),data=JSON.stringify({draft:state.draft,case:state.caseContext,sources:selectedSources().map(s=>({id:s.id,title:s.title,kind:s.kind,citation:s.citation,status:s.status}))},null,2),print=`<!doctype html><html><head><meta charset="utf-8"><title>${esc(state.draft.title)}</title><style>body{font-family:Georgia,serif;margin:.7in;color:#111}h1{text-align:center}h2{font-size:16px;text-transform:uppercase;margin-top:24px}p,li{font-size:12pt;line-height:1.55}table{border-collapse:collapse;width:100%}th,td{padding:8px;border-bottom:1px solid #ccc;text-align:left}</style></head><body>${reportHtmlBody(false)}</body></html>`,index=attorney,readme=`ARC Offline Case Dashboard\n\nOpen index.html in a modern browser. No internet connection is required.\nThe formal PDF is generated separately from the Report Package Builder by using Print / Save PDF.\nAll report views are derived from the same master report content.\n`,hashes={"index.html":await sha256Text(index),"report/report_data.json":await sha256Text(data),"report/report_print.html":await sha256Text(print),"README.html":await sha256Text(`<pre>${esc(readme)}</pre>`)};const manifest=JSON.stringify({schema:"arc-offline-report-package",version:1,reportId:state.draft.id,caseId:caseId(),generatedAt:new Date().toISOString(),files:Object.keys(hashes),hashAlgorithm:"SHA-256"},null,2),checks=Object.keys(hashes).map(k=>hashes[k]+"  "+k).join("\n");download(safeName()+"_Offline_Report_Dashboard.zip",makeZip({"index.html":index,"report/report_data.json":data,"report/report_print.html":print,"README.html":`<!doctype html><meta charset="utf-8"><title>ARC Package Read Me</title><pre>${esc(readme)}</pre>`,"integrity/manifest.json":manifest,"integrity/sha256_checksums.txt":checks}));setStatus("Offline dashboard ZIP generated from the current master report.")}
function masterReportText(){capture();const parts=[];if(state.draft.summary)parts.push("EXECUTIVE SUMMARY\n"+state.draft.summary);SECTION_DEFS.forEach(x=>{const body=clean(state.draft.sections[x[0]]);if(body)parts.push(x[1].toUpperCase()+"\n"+body)});return parts.join("\n\n")}
function sendToReview(){
  capture();
  if(!window.ARCUnified||typeof window.ARCUnified.saveReport!=="function"){setStatus("ARC report review bridge is unavailable.","error");return}
  const text=masterReportText();
  if(!text.trim()){setStatus("Draft at least one report section before sending to review.","error");return}
  const payload={
    id:state.draft.reviewReportId||undefined,
    title:state.draft.title||"Final Investigation Report",
    reportType:state.draft.type||"Final Investigation Report",
    text:text,
    html:reportHtmlBody(false),
    source:"22_Report_Package_Builder.html",
    caseContext:state.caseContext,
    reviewStatus:"pending",
    selectedMediaOnly:true,
    masterReportId:state.draft.id,
    sourceIds:state.draft.selectedSourceIds.slice()
  };
  Promise.resolve(window.ARCUnified.saveReport(payload)).then(saved=>{
    state.draft.reviewReportId=(saved&&saved.id)||payload.id||state.draft.reviewReportId;
    saveDraft();
    setStatus("Report sent to the ARC Review Inbox as pending. Approve it in the case workspace before Edit PDF/final release.");
    try{window.parent&&window.parent!==window&&window.parent.postMessage({type:"ARC_REPORT_SAVED",report:saved||payload},(location.protocol==="http:"||location.protocol==="https:")?location.origin:"*")}catch(e){}
  }).catch(e=>setStatus("Could not send report to review: "+e.message,"error"));
}
function bind(){document.querySelector(".rp-tabs").addEventListener("click",e=>{const b=e.target.closest("button[data-view]");if(!b)return;capture();document.querySelectorAll(".rp-tabs button").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".rp-view").forEach(x=>x.classList.toggle("active",x.dataset.panel===b.dataset.view));if(b.dataset.view==="review")renderPreview();if(b.dataset.view==="outputs")renderManifest()});$("rpReload").addEventListener("click",init);$("rpDraftAI").addEventListener("click",draftWithAI);$("rpSave").addEventListener("click",saveDraft);$("rpSendReview").addEventListener("click",sendToReview);$("rpPrint").addEventListener("click",()=>{renderPreview();window.print()});$("rpPdf").addEventListener("click",()=>{renderPreview();window.print()});$("rpHtml").addEventListener("click",()=>{capture();download(safeName()+"_Interactive_Attorney_Report.html",new Blob([attorneyDocument()],{type:"text/html"}));setStatus("Interactive attorney HTML downloaded.")});$("rpZip").addEventListener("click",()=>buildZip().catch(e=>setStatus("ZIP generation failed: "+e.message,"error")))}

/* Claude drafts the narrative once, from approved material only. The result
   lands in the same textareas an investigator edits; nothing is auto-locked and
   no output format regenerates its own text. */
function showDraftNotes(lines,tone){const box=$("rpDraftNotes");if(!lines||!lines.length){box.hidden=true;box.innerHTML="";return}box.hidden=false;box.className="rp-draft-notes "+(tone||"");box.innerHTML=lines.map(l=>`<div>${esc(l)}</div>`).join("")}
async function draftWithAI(){
  const btn=$("rpDraftAI");
  if(!window.ARCFinalReport){setStatus("The report writer is not loaded. Check that arc_final_report_writer.js is included.","error");return}
  const filled=Object.keys(state.draft.sections).filter(k=>clean(state.draft.sections[k]));
  if(filled.length&&!window.confirm("Sections already contain text. Drafting will replace the sections the writer produces. Continue?"))return;
  btn.disabled=true;const label=btn.textContent;btn.textContent="Drafting...";
  showDraftNotes([]);
  setStatus("Claude is drafting from the approved record. Nothing is locked until you review it.");
  try{
    const out=await window.ARCFinalReport.draft({caseId:caseId()});
    Object.keys(out.sections||{}).forEach(k=>{if(k in state.draft.sections)state.draft.sections[k]=clean(out.sections[k],50000)});
    renderSections();renderPreview();
    const notes=[`Drafted from ${out.approvedFactCount} approved fact(s) and ${out.approvedFindingCount} approved finding(s).`].concat(out.warnings||[]);
    if(out.notes)notes.push(out.notes);
    notes.push("This is a draft. Review every section and confirm each source tag before you save the master report.");
    showDraftNotes(notes,(out.warnings||[]).length?"warn":"");
    setStatus("Draft generated. Review it before saving.");
  }catch(e){
    showDraftNotes([e.message],"error");
    setStatus("Draft not generated: "+e.message,"error");
  }finally{btn.disabled=false;btn.textContent=label}
}
async function init(){try{state.caseContext=getCase();$("rpCaseLabel").textContent=clean(state.caseContext.matter||state.caseContext.caseName||state.caseContext.clientName||"No active case selected")+(state.caseContext.docket||state.caseContext.docketNumber?" · "+clean(state.caseContext.docket||state.caseContext.docketNumber):"");await collectSources();loadDraft();hydrate();renderSources();renderSections();renderPreview();setStatus(state.sources.length?"Case materials loaded. Select approved sources and build the master report.":"No shared case sources were found. The builder remains available for manual drafting.",state.sources.length?"":"error")}catch(e){setStatus("The report builder could not load: "+e.message,"error")}}
document.addEventListener("DOMContentLoaded",function(){bind();init()});
})();
